---
title: "timeseries-1"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Line Plot


```{r}
library(tsibbledata)
library(tidyverse)
data(olympic_running)
```

```{r}
ggplot(pelt) +
  geom_line(aes(Year, Lynx))

ggplot(pelt) +
  geom_area(aes(Year, Lynx))
```

```{r}
library(sugrrants)
library(lubridate)
vic_elec <- vic_elec %>%
  filter(year(Date) == "2013", month(Date) < 4) %>%
  mutate(hour = hour(Time))

vic_monthly <- vic_elec %>%
  frame_calendar(x = hour, y = Demand, date = Date)
p <- ggplot(vic_monthly) +
  geom_line(aes(.hour, .Demand, group = Date))
prettify(p)

vic_monthly <- vic_elec %>%
  frame_calendar(x = 1, y = 1, date = Date)

p <- ggplot(vic_monthly) +
  geom_tile(aes(.x, .y, fill = Demand)) +
  scale_fill_distiller(direction = 1) +
  coord_fixed(1/3) +
  theme(legend.position = "bottom")
prettify(p)

vic_daily <- vic_elec %>%
  frame_calendar(x = Temperature, y = Demand, date = Date, calendar = "daily")
p <- ggplot(vic_daily) +
  geom_point(aes(.Temperature, .Demand, col = hour, group = Date), size = 0.2)
prettify(p)

```

```{r}
p <- ggplot(centre_calendar) +
  geom_line(aes(.Time, .Hourly_Counts, group = Date))
prettify(p)
```

```{r}
data(tourism)
tourism <- tourism %>%
  filter(Purpose == "Holiday")

region_totals <- tourism %>%
  as_tibble() %>%
  group_by(Region) %>%
  summarise(total_trips = sum(Trips)) %>%
  arrange(-total_trips)

tourism %>%
  filter(Region %in% region_totals$Region[1:5]) %>%
  ggplot() +
  geom_line(aes(Quarter, Trips, col = Region))

tourism %>%
  filter(Region %in% region_totals$Region[1:16]) %>%
  ggplot() +
  geom_line(aes(Quarter, Trips)) +
  facet_wrap(~ reorder(Region, -Trips))
```

```{r}
tourism %>%
  filter(Region %in% region_totals$Region[1:16]) %>%
  ggplot() +
  geom_tile(aes(Quarter, reorder(Region, Trips), fill = Trips)) +
  scale_fill_distiller(direction = 1)
```

```{r}
library(ggHoriPlot)

cutpoints <- seq(0, 1000, by = 101)
tourism %>%
  filter(Region %in% region_totals$Region[1:16]) %>%
  ggplot() +
  geom_horizon(aes(Quarter, Trips, fill = ..Cutpoints..), origin = 350, horizonscale = cutpoints) +
  scale_fill_hcl(palette = 'RdBu') +
  facet_grid(reorder(Region, -Trips) ~ .) +
  theme(strip.text.y = element_text(angle = 0))
ggsave("~/Downloads/ts.png", dpi = 1000)
```

```{r}
library(ggstream)
library(colorspace)
xmen <- read_csv("x-men.csv")
pal <- c(
  "#8E038E", lighten("#8E038E", .2, space = "HLS"),
  "#C20008", lighten("#C20008", .2, space = "HLS"),
  "#13AFEF", lighten("#13AFEF", .25, space = "HLS"),
  "#595A52", lighten("#595A52", .15, space = "HLS"),
  "#FFB400", lighten("#FFB400", .25, space = "HLS")
)

ggplot(xmen) +
  geom_area(aes(issue, depicted, col = interaction(costume, char_popular), fill = interaction(costume, char_popular))) +
  scale_fill_manual(values = pal) +
  scale_color_manual(values = pal) +
  theme(legend.position = "bottom")

ggplot(xmen) +
  geom_stream(aes(issue, depicted, col = interaction(costume, char_popular), fill = interaction(costume, char_popular))) +
  scale_fill_manual(values = pal) +
  scale_color_manual(values = pal) +
  theme(legend.position = "bottom")
```


```{r}
library(ggalluvial)
library(scales)

refugees <- read_csv("refugees.csv")
ggplot(refugees) +
  geom_stream(aes(year, refugees, fill = country), bw = 1) +
  facet_wrap(~ region, scale = "free_y")

ggplot(refugees) +
  geom_alluvium(aes(year, refugees, fill = country, alluvium = country), decreasing = FALSE, alpha = 0.9) +
  facet_wrap(~ region, scale = "free_y") +
  scale_y_continuous(labels = label_number(scale_cut = cut_long_scale()))
 
```




1. Single time series
	1. Line plot
	2. Area chart
	3. Calendar plot
2. Multiple time series
	1. Multiple lines plot
	2. Faceted lines plot
	3. Heatmap
	4. Horizon plot
	5. Theme river
	6. Alluvial diagram
	7. Embeddings plot (PCA)
